
package introsde.assignment3.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://soap.assignment3.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param person
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(name = "idPerson", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/createPersonRequest", output = "http://soap.assignment3.introsde/People/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(name = "idPerson", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/updatePersonRequest", output = "http://soap.assignment3.introsde/People/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param idPerson
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/deletePersonRequest", output = "http://soap.assignment3.introsde/People/deletePersonResponse")
    public long deletePerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson);

    /**
     * 
     * @param idPerson
     * @param type
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferencesByType", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferencesByType")
    @ResponseWrapper(localName = "readPersonPreferencesByTypeResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferencesByTypeResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonPreferencesByTypeRequest", output = "http://soap.assignment3.introsde/People/readPersonPreferencesByTypeResponse")
    public List<Activity> readPersonPreferencesByType(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPreferencesRequest", output = "http://soap.assignment3.introsde/People/readPreferencesResponse")
    public List<Activity> readPreferences();

    /**
     * 
     * @param idPerson
     * @param idActivity
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferencesById", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferencesById")
    @ResponseWrapper(localName = "readPersonPreferencesByIdResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferencesByIdResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonPreferencesByIdRequest", output = "http://soap.assignment3.introsde/People/readPersonPreferencesByIdResponse")
    public Activity readPersonPreferencesById(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson,
        @WebParam(name = "idActivity", targetNamespace = "")
        long idActivity);

    /**
     * 
     * @param idPerson
     * @param activity
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "savePersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreferences")
    @ResponseWrapper(localName = "savePersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/savePersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/savePersonPreferencesResponse")
    public long savePersonPreferences(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

    /**
     * 
     * @param idPerson
     * @param activity
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "updatePersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreferences")
    @ResponseWrapper(localName = "updatePersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/updatePersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/updatePersonPreferencesResponse")
    public Activity updatePersonPreferences(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

    /**
     * 
     * @param idPerson
     * @param activity
     * @param value
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "evaluatePersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreferences")
    @ResponseWrapper(localName = "evaluatePersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/evaluatePersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/evaluatePersonPreferencesResponse")
    public Activity evaluatePersonPreferences(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity,
        @WebParam(name = "value", targetNamespace = "")
        int value);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "")
    @RequestWrapper(localName = "getBestPersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferences")
    @ResponseWrapper(localName = "getBestPersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/getBestPersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/getBestPersonPreferencesResponse")
    public List<Activity> getBestPersonPreferences(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson);

    /**
     * 
     * @param idActivity
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "createActivity", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreateActivity")
    @ResponseWrapper(localName = "createActivityResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreateActivityResponse")
    @Action(input = "http://soap.assignment3.introsde/People/createActivityRequest", output = "http://soap.assignment3.introsde/People/createActivityResponse")
    public Activity createActivity(
        @WebParam(name = "idActivity", targetNamespace = "")
        Activity idActivity);

    /**
     * 
     * @param idPerson
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonRequest", output = "http://soap.assignment3.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        long idPerson);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonListResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonListRequest", output = "http://soap.assignment3.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

}
